name: replication
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python>=3.8
  - nextflow>=22.04.0
  - fastp
  - bowtie2
  - pandas>=1.0
  - samtools
  - multiqc
  - pip
  - numpy>=1.19.1
  - pysam>=0.16.0.1
  - scipy>=1.5.2
  - matplotlib>=3.3.2
  - pip:
    - git+https://github.com/tyjo/coptr
