name: metagenomics
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - fastp
  - megahit
  - minimap2
  - prodigal
  - metabat2
  - salmon
  - loguru
  - pandas
  - samtools
  - multiqc
