name: metagenomics
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python>=3.8
  - nextflow>=20.10.0
  - fastp
  - megahit
  - kraken2>=2.1.0
  - bracken
  - krakentools
  - bowtie2
  - prodigal
  - metabat2
  - salmon
  - loguru
  - pandas
  - samtools
  - multiqc
  - biopython
  - mmseqs2
  - bioconda::cat
  - pip
  - matplotlib
  - numpy
  - scipy
  - pysam
  - pip:
    - eggnog-mapper
    - git+https://github.com/tyjo/coptr
