name: metagenomics
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - fastp
  - megahit
  - kraken2>=2.1.0
  - bracken
  - krakentools
  - bowtie2
  - prodigal
  - metabat2
  - salmon
  - loguru
  - pandas
  - samtools
  - multiqc
  - biopython
  - bioconda::cat
  - pip
  - matplotlib
  - numpy
  - pysam
  - scipy
  - pip:
    - eggnog-mapper
