name: metagenomics
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - fastp
  - megahit
  - minimap2
  - prodigal
  - metabat2
  - salmon
  - snakemake-minimal
  - pandas
  - samtools
