manifest: "manifest.csv"
raw: "data/raw/"
preprocess: "data/preprocessed/"
assembly: "data/assembled/"
align: "data/aligned/"
binning: "data/binned/"
annotate: "data/annotated/"
txn_align: "data/txn_aligned/"
em_count: "data/counted/"
merge: "data/function_counts.csv"
